<?php

namespace Database\Seeders;

use App\Models\Student;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class StudentSeeder extends Seeder
{
    public function run(): void
    {
        // Hapus semua data siswa terlebih dahulu agar seed selalu bersih
        Student::query()->delete();

        $students = [
            [
                'nis' => '2503486',
                'name' => 'Jeni Reninda',
                'username' => 'jenerininda',
                'email' => 'jenerininda@gmail.com',
                'password' => Hash::make('password'),
                'date_of_birth' => '2010-06-21',
                'class_name' => 'X',
                'major' => 'Teknik Elektronika Industri',
                'status' => 'aktif',
                'nfc_type' => 'handphone',
                    'uid_kartu' => '539EA8F8930001',
                'phone' => '085126368188',
            ],
            [
                'nis' => '2503481',
                'name' => 'Dika Mustafa',
                'username' => 'dikamustafa',
                'email' => 'dikamustafatexpur@gmail.com',
                'password' => Hash::make('password'),
                'date_of_birth' => '2009-02-05',
                'class_name' => 'X',
                'major' => 'Teknik Elektronika Industri',
                'status' => 'aktif',
                'nfc_type' => 'handphone',
                'uid_kartu' => '5343DBF8930001',
                'phone' => '085129460626',
            ],
            [
                'nis' => '2503488',
                'name' => 'Maram Isa Hussein',
                'username' => 'mramissa8',
                'email' => 'mramissa8@gmail.com',
                'password' => Hash::make('password'),
                'date_of_birth' => '2008-10-27',
                'class_name' => 'X',
                'major' => 'Teknik Elektronika Industri',
                'status' => 'aktif',
                'nfc_type' => 'handphone',
                'uid_kartu' => '53289AF8930001',
                'phone' => '085219151580',
            ],
            [
                'nis' => '2503478',
                'name' => 'Citra Nur Assyifa',
                'username' => 'citranurassyifa',
                'email' => 'citranurassyifa@gmail.com',
                'password' => Hash::make('password'),
                'date_of_birth' => '2010-01-26',
                'class_name' => 'X',
                'major' => 'Teknik Elektronika Industri',
                'status' => 'aktif',
                'nfc_type' => 'handphone',
                'uid_kartu' => '53B8F8F8930001',
                'phone' => '089534870021',
            ],
            [
                'nis' => '2503479',
                'name' => 'Delly Aprilansyah',
                'username' => 'apindelly',
                'email' => 'apindelly@gmail.com',
                'password' => Hash::make('password'),
                'date_of_birth' => '2010-04-04',
                'class_name' => 'X',
                'major' => 'Teknik Elektronika Industri',
                'status' => 'aktif',
                'nfc_type' => 'handphone',
                'uid_kartu' => '532AEAF8930001',
                'phone' => '085814761732',
            ],
            [
                'nis' => '2503489',
                'name' => 'Muhamad Al Fatir',
                'username' => 'alfatirm4288',
                'email' => 'alfatirm4288@gmail.com',
                'password' => Hash::make('password'),
                'date_of_birth' => '2009-12-20',
                'class_name' => 'X',
                'major' => 'Teknik Elektronika Industri',
                'status' => 'aktif',
                'nfc_type' => 'handphone',
                'uid_kartu' => '539592F8930001',
                'phone' => '085870530995',
            ],
            [
                'nis' => '2503485',
                'name' => 'Irzi Rivaldie',
                'username' => 'muhidinjaelani308',
                'email' => 'muhidinjaelani308@gmail.com',
                'password' => Hash::make('password'),
                'date_of_birth' => '2010-09-19',
                'class_name' => 'X',
                'major' => 'Teknik Elektronika Industri',
                'status' => 'aktif',
                'nfc_type' => 'handphone',
                'uid_kartu' => '53D9B6F8930001',
                'phone' => '085890244274',
            ],
            [
                'nis' => '2503472',
                'name' => 'Adi Pramana Maheswa',
                'username' => 'click1857',
                'email' => 'click1857@gmail.com',
                'password' => Hash::make('password'),
                'date_of_birth' => '2009-04-24',
                'class_name' => 'X',
                'major' => 'Teknik Elektronika Industri',
                'status' => 'aktif',
                'nfc_type' => 'handphone',
                'uid_kartu' => '538F23F9930001',
                'phone' => '083840471301',
            ],
            [
                'nis' => '2503484',
                'name' => 'Fian Hamiduputra',
                'username' => 'hamidupratifan',
                'email' => 'hamidupratifan@gmail.com',
                'password' => Hash::make('password'),
                'date_of_birth' => '2009-12-21',
                'class_name' => 'X',
                'major' => 'Teknik Elektronika Industri',
                'status' => 'aktif',
                'nfc_type' => 'handphone',
                'uid_kartu' => '531BBEF8930001',
                'phone' => '08568627041',
            ],
            [
                'nis' => '2503540',
                'name' => 'Dani Damara',
                'username' => 'danidamara781',
                'email' => 'danidamara781@gmail.com',
                'password' => Hash::make('password'),
                'date_of_birth' => '2010-04-02',
                'class_name' => 'X',
                'major' => 'Teknik Elektronika Industri',
                'status' => 'aktif',
                'nfc_type' => 'handphone',
                'uid_kartu' => '5379F1F8930001',
                'phone' => '08582573496',
            ],
            [
                'nis' => '2503480',
                'name' => 'Denis Firmansyah',
                'username' => 'denisfirmansyah118',
                'email' => 'denisfirmansyah118@gmail.com',
                'password' => Hash::make('password'),
                'date_of_birth' => '2008-10-25',
                'class_name' => 'X',
                'major' => 'Teknik Elektronika Industri',
                'status' => 'aktif',
                'nfc_type' => 'handphone',
                'uid_kartu' => '5384E2F8930001',
                'phone' => '085939422736',
            ],
            [
                'nis' => '2503476',
                'name' => 'Azka Azmi Damarwidad',
                'username' => 'akzaazmi90',
                'email' => 'akzaazmi90@gmail.com',
                'password' => Hash::make('password'),
                'date_of_birth' => '2009-08-04',
                'class_name' => 'X',
                'major' => 'Teknik Elektronika Industri',
                'status' => 'aktif',
                'nfc_type' => 'handphone',
                'uid_kartu' => '53210EF9930001',
                'phone' => '083150734603',
            ],
            [
                'nis' => '2503497',
                'name' => 'Thasen Mahesa Djenar',
                'username' => 'tasenshoft',
                'email' => 'tasenshoft@gmail.com',
                'password' => Hash::make('password'),
                'date_of_birth' => '2010-06-13',
                'class_name' => 'X',
                'major' => 'Teknik Elektronika Industri',
                'status' => 'aktif',
                'nfc_type' => 'handphone',
                'uid_kartu' => '53FC55F8930001',
                'phone' => '083137535113',
            ],
            [
                'nis' => '2503491',
                'name' => 'Rizqon Syifa Alastary',
                'username' => 'rizqonsyifaalarsty',
                'email' => 'rizqonsyifaalarsty@gmail.com',
                'password' => Hash::make('password'),
                'date_of_birth' => '2009-10-02',
                'class_name' => 'X',
                'major' => 'Teknik Elektronika Industri',
                'status' => 'aktif',
                'nfc_type' => 'handphone',
                'uid_kartu' => '530181F8930001',
                'phone' => '083869482953',
            ],
            [
                'nis' => '2503473',
                'name' => 'Adriene Delicia Arends',
                'username' => 'deliciaarends1933',
                'email' => 'deliciaarends1933@gmail.com',
                'password' => Hash::make('password'),
                'date_of_birth' => '2010-01-13',
                'class_name' => 'X',
                'major' => 'Teknik Elektronika Industri',
                'status' => 'aktif',
                'nfc_type' => 'handphone',
                'uid_kartu' => '53F61CF9930001',
                'phone' => '08586299700',
            ],
            [
                'nis' => '2503483',
                'name' => 'Exsel Feby Susanti',
                'username' => 'tini2182927',
                'email' => 'tini2182927@gmail.com',
                'password' => Hash::make('password'),
                'date_of_birth' => '2009-02-28',
                'class_name' => 'X',
                'major' => 'Teknik Elektronika Industri',
                'status' => 'aktif',
                'nfc_type' => 'handphone',
                'uid_kartu' => '53BAC5F8930001',
                'phone' => '081399021885',
            ],
            [
                'nis' => '2503496',
                'name' => 'Tasya Maharani',
                'username' => 'tmharani998',
                'email' => 'tmharani998@gmail.com',
                'password' => Hash::make('password'),
                'date_of_birth' => '2010-01-27',
                'class_name' => 'X',
                'major' => 'Teknik Elektronika Industri',
                'status' => 'aktif',
                'nfc_type' => 'handphone',
                'uid_kartu' => '53565DF8930001',
                'phone' => '081400612932',
            ],
            [
                'nis' => '2503500',
                'name' => 'Zahra Putri',
                'username' => 'zhraputri368',
                'email' => 'zhraputri368@gmail.com',
                'password' => Hash::make('password'),
                'date_of_birth' => '2010-07-29',
                'class_name' => 'X',
                'major' => 'Teknik Elektronika Industri',
                'status' => 'aktif',
                'nfc_type' => 'handphone',
                'uid_kartu' => '533741F8930001',
                'phone' => '087885028541',
            ],
            [
                'nis' => '2503492',
                'name' => 'Risma Auliawa',
                'username' => 'rismaauliawati65',
                'email' => 'rismaauliawati65@gmail.com',
                'password' => Hash::make('password'),
                'date_of_birth' => '2009-06-22',
                'class_name' => 'X',
                'major' => 'Teknik Elektronika Industri',
                'status' => 'aktif',
                'nfc_type' => 'handphone',
                'uid_kartu' => '537D79F8930001',
                'phone' => '085718742075',
            ],
            [
                'nis' => '2503490',
                'name' => 'Nabila Sipa Romansyah',
                'username' => 'bilabila76445',
                'email' => 'bilabila76445@gmail.com',
                'password' => Hash::make('password'),
                'date_of_birth' => '2009-08-05',
                'class_name' => 'X',
                'major' => 'Teknik Elektronika Industri',
                'status' => 'aktif',
                'nfc_type' => 'handphone',
                'uid_kartu' => '538D87F8930001',
                'phone' => '088901791074',
            ],
            [
                'nis' => '2503477',
                'name' => 'Bintang Anugrah Pratan',
                'username' => 'bintangpratama83962',
                'email' => 'bintangpratama83962@gmail.com',
                'password' => Hash::make('password'),
                'date_of_birth' => '2009-12-01',
                'class_name' => 'X',
                'major' => 'Teknik Elektronika Industri',
                'status' => 'aktif',
                'nfc_type' => 'handphone',
                'uid_kartu' => '53E406F9930001',
                'phone' => '083817086023',
            ],
            [
                'nis' => '2503494',
                'name' => 'Salwa Septianti',
                'username' => 'septiantisalwa09',
                'email' => 'septiantisalwa09@gmail.com',
                'password' => Hash::make('password'),
                'date_of_birth' => '2010-09-23',
                'class_name' => 'X',
                'major' => 'Teknik Elektronika Industri',
                'status' => 'aktif',
                'nfc_type' => 'handphone',
                'uid_kartu' => '536372F8930001',
                'phone' => '083117960091',
            ],
            [
                'nis' => '2503474',
                'name' => 'Ajeng Yulia',
                'username' => 'ajengyulia708',
                'email' => 'ajengyulia708@gmail.com',
                'password' => Hash::make('password'),
                'date_of_birth' => '2009-09-18',
                'class_name' => 'X',
                'major' => 'Teknik Elektronika Industri',
                'status' => 'aktif',
                'nfc_type' => 'handphone',
                'uid_kartu' => '536415F9930001',
                'phone' => '083841582414',
            ],
            [
                'nis' => '2503499',
                'name' => 'Yasin Fadilah',
                'username' => 'yasinyasinfadilah7',
                'email' => 'yasinyasinfadilah7@gmail.com',
                'password' => Hash::make('password'),
                'date_of_birth' => '2010-09-24',
                'class_name' => 'X',
                'major' => 'Teknik Elektronika Industri',
                'status' => 'aktif',
                'nfc_type' => 'handphone',
                'uid_kartu' => '53563DF4930001',
                'phone' => '089561940436',
            ],
            [
                'nis' => '2503482',
                'name' => 'Euis Maryati',
                'username' => 'euismaryati431',
                'email' => 'euismaryati431@gmail.com',
                'password' => Hash::make('password'),
                'date_of_birth' => '2009-09-10',
                'class_name' => 'X',
                'major' => 'Teknik Elektronika Industri',
                'status' => 'aktif',
                'nfc_type' => 'handphone',
                'uid_kartu' => '5302CDF8930001',
                'phone' => '083182638690',
            ],
            [
                'nis' => '2503491',
                'name' => 'Nurwan Fadilah',
                'username' => 'nurwanfadhil92',
                'email' => 'nurwanfadhil92@gmail.com',
                'password' => Hash::make('password'),
                'date_of_birth' => '2009-06-21',
                'class_name' => 'X',
                'major' => 'Teknik Elektronika Industri',
                'status' => 'aktif',
                'nfc_type' => 'handphone',
                'uid_kartu' => '530181F8930001',
                'phone' => '085781543157',
            ],
            [
                'nis' => '2503487',
                'name' => 'Lailatun Novitasari',
                'username' => 'budicahngawi34',
                'email' => 'budicahngawi34@gmail.com',
                'password' => Hash::make('password'),
                'date_of_birth' => '2010-03-02',
                'class_name' => 'X',
                'major' => 'Teknik Elektronika Industri',
                'status' => 'aktif',
                'nfc_type' => 'handphone',
                'uid_kartu' => '5362A1F8930001',
                'phone' => '081410398967',
            ],
            [
                'nis' => '2503495',
                'name' => 'Sulthan Febrian',
                'username' => 'sulthanafeibrianng',
                'email' => 'sulthanafeibrianng@gmail.com',
                'password' => Hash::make('password'),
                'date_of_birth' => '2010-02-05',
                'class_name' => 'X',
                'major' => 'Teknik Elektronika Industri',
                'status' => 'aktif',
                'nfc_type' => 'handphone',
                'uid_kartu' => '536C64F8930001',
                'phone' => '088994385785',
            ],
        ];

        foreach ($students as $student) {
            if (empty($student['uid_kartu'])) {
                $student['uid_kartu'] = 'UID-' . $student['nis'];
            }

            Student::updateOrCreate(
                ['nis' => $student['nis']],
                $student
            );
        }
    }
}

